### ISSUE TITLE
playback

### ISSUE THREAD

**Issue by mmccallum** [fostertheweb/spotify-web-sdk#14]
Thanks for this.  I'm curious as to why you didn't include the playback API.  Is it overly difficult?  If so, what problems did you see?

**Comment by fostertheweb** [comment]
Hi @mmccallum! I'm sorry I never saw a notification for you creating this issue. There is already [this package](https://www.npmjs.com/package/@types/spotify-web-playback-sdk) that has the types for the Spotify Web Playback SDK. How you integrate the library can depend on your front end framework, and there is already a library for React: https://github.com/gilbarbara/react-spotify-web-playback
