### ISSUE TITLE
Support asynchronous methods in `ICacheStore`

### ISSUE THREAD

**Issue by therealsujitk** [fostertheweb/spotify-web-sdk#16]
It would be great if asynchronous methods were supported in `ICacheStore` for when developers need to implement custom caching that cannot be called synchronously.

- Original issue - [spotify/spotify-web-api-ts-sdk#114](https://github.com/spotify/spotify-web-api-ts-sdk/issues/114)
- Pull Request - [spotify/spotify-web-api-ts-sdk#115](https://github.com/spotify/spotify-web-api-ts-sdk/pull/115)

@fostertheweb it would be great if you could review & test this PR and merge it to this fork if you think everything looks good. Thanks!

**Comment by fostertheweb** [comment]
Sorry, I need to figure out my GitHub notifications. Could we avoid making this many changes by adding an `IAsyncCacheStore`?

```ts
export interface IAsyncCacheStore {
  get(key: string): Promise<string | null>;
  set(key: string, value: string): Promise<void>;
  remove(key: string): Promise<void>;
}
```

**Comment by therealsujitk** [comment]
@fostertheweb we could create a separate `IAsyncCacheStore` instead of modifying the current one, but it would be pointless to be honest. The rest of the changes will have to remain the same since they still have to be `await`ed.

Since I made the functions in `ICacheStore` asynchronous, we need to `await` all the function calls to this, and some of those function calls weren't in `async` functions itself, so they had to be made asynchronous as well and so on.

If we create a separate `IAsyncCacheStore`, we'll need to make even more changes so typescript knows that the cache store can be either `ICacheStore` or `IAsyncCacheStore`. I feel the current modification is better as it also supports the current synchronous cache store and doesn't include any breaking changes (except maybe the asynchronous logout function [as mentioned in the third point under **Changes**](https://github.com/spotify/spotify-web-api-ts-sdk/pull/115)).

**Comment by fostertheweb** [comment]
Ah yeah for whatever reason I was thinking you created a fully custom caching strategy, instead of extending `GenericCache`. This makes sense, I'll copy the PR over here.

**Comment by fostertheweb** [comment]
Solved with #18

**Comment by fostertheweb** [comment]
@therealsujitk Version `1.3.0` published to npm

**Comment by therealsujitk** [comment]
@fostertheweb Thankyou!
